services:
  db-mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: classify
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - private_network

  backend:
    build: ./backend
    container_name: spring_maven
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/classify
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db-mysql
    networks:
      - private_network

  frontend:
    build: ./frontend
    container_name: react_nginx
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend
    networks:
      - private_network

volumes:
  db_data:

networks:
  private_network:
    name: private_network
    driver: bridge